# Generated by Django 2.1.3 on 2018-11-16 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=55)),
                ('slug', models.SlugField(max_length=55)),
                ('is_company', models.BooleanField(default=False)),
                ('is_independent', models.BooleanField(default=False)),
                ('about', models.TextField()),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('line_id', models.CharField(blank=True, max_length=25, unique=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
