# Generated by Django 2.1.3 on 2018-11-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificicationdocument',
            name='document',
            field=models.FileField(upload_to='documents'),
        ),
    ]
