# Generated by Django 2.1.3 on 2018-11-17 18:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181117_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='logo',
            field=models.ImageField(default='logos/default.jpeg', upload_to=accounts.models.user_directory_path),
        ),
    ]
