# Generated by Django 2.1.3 on 2018-11-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='furnishing',
            field=models.CharField(choices=[('Unfurnished', 'Unfurnished'), ('Semi furnished', 'Semi Furnished'), ('Fully furnished', 'Fully Furnished')], default='Unfurnished', max_length=25),
        ),
    ]
