# Generated by Django 2.1.3 on 2018-11-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20181118_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=255)),
                ('floors', models.IntegerField()),
                ('shopping_mall', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('jogging_track', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
