# Generated by Django 2.1.3 on 2018-11-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(default='properties/default.jpg', upload_to='properties/apartments'),
        ),
    ]
